main: com.tistory.hornslied.evitaonline.Main
name: EvitaOnline
version: 1.0
author: Ludwig Hornslied
depend: [Towny, Vault]
commands:
  cafe:
  website:
  hack:
  limit:
  alert:
  evitatowny:
    sidge:
      stop:
    warlog:
      delete:
  ac:
    new:
    show: